name: Update Clash Rules

on:
  schedule:
    - cron: '0 15 * * 0'
  workflow_dispatch:

jobs:
  update-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install requests pyyaml

      - name: Run rule merge script
        run: python rule_merge.py

      - name: Ensure all files exist
        run: |
          for file in Proxy.txt Direct.txt Reject.txt Ai.txt merged_rules.conf; do
            touch "$file"
          done

      - name: Create a temporary directory
        run: mkdir -p temp

      - name: Move files to temp directory
        run: |
          mv Proxy.txt Direct.txt Reject.txt Ai.txt merged_rules.conf README.md temp/ || echo "Some files are missing"

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git checkout --orphan gh-pages
          git reset --hard
          mv temp/* ./
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages

      - name: Switch back to main branch
        run: git checkout main

      - name: Copy README.md from gh-pages
        run: cp temp/README.md ./

      - name: Commit changes to main branch
        run: |
          git add README.md
          git commit -m "Update README with new URLs" || echo "No changes to commit"
          git push origin main

      - name: Cleanup temp directory
        run: rm -rf temp
