name: Update Clash Rules

on:
  schedule:
    - cron: '0 15 * * 0'
  workflow_dispatch:

jobs:
  update-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install requests pyyaml

      - name: Run rule merge script
        run: python rule_merge.py

      - name: Ensure all files exist
        run: |
          for file in Proxy.txt Direct.txt Reject.txt Ai.txt merged_rules.conf; do
            touch "$file"
          done

      - name: Update README with fixed URLs
        run: |
          echo "## Fixed URLs" > README.md
          beijing_time=$(TZ='Asia/Shanghai' date '+%Y年%m月%d日%H时%M分%S秒')
          echo "更新于北京时间 $beijing_time" >> README.md
          for file in Proxy.txt Direct.txt Reject.txt Ai.txt merged_rules.conf; do
            echo "- $file: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/$file" >> README.md
          done

      - name: Commit and push changes to main branch
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit -m "Update rules and README" || echo "No changes to commit"
          git push origin main
